### ISSUE TITLE
Use-cases for this library

### ISSUE THREAD

**Issue by sobolevn** [dry-python/mappers#2]
Converters should cover:
1. From domain entities to ORM models
2. From ORM models to domain entities

Common ORM operations:
1. Read
2. Create
3. Update
4. Delete

## Samples

I will be using this code sample for all examples:

```python
# Domain entities

import attr


@attr.s(slots=True, auto_attribs=True)
class Project(object):
  uid: int
  name: str
  path: str
  url: str


@attr.s(slots=True, auto_attribs=True)
class Issue(object):
  uid: int
  project: Project
```

And models:

```python
# ORM, models.py

class ProjectModel(models.Model):
    uid = models.PositiveIntegerField(unique=True)
    path = models.CharField(max_length=200, unique=True)
    name = models.CharField(max_length=200)
    url = models.URLField()

    # Excluded from domain, utility:
    is_active = models.BooleanField(default=False)


class IssueModel(models.Model):
    uid = models.PositiveIntegerField(unique=True)
    project = models.ForeignKey('Project', related_name='issues')
```

## Read

```python
from converters import build_converter

to_model = build_converter(...)
from_model = build_converter(...)

# Some repository logic:

def load_issue(issue_uid: int) -> Issue:
     return from_model(IssueModel.objects.get(uid=uid))
```

## Create

```python
def save_issue(issue: Issue, **kwargs) -> IssueModel:
     model = to_model(issue)
     model.save(**kwargs)
     return model
```

## Update

```python
project = load_project(1)  # similar to `load_issue()`
project.name = 'New name'

def update_project(project: Project) -> ProjectModel:
     model = to_project_model(project, existing=True)
     model.save()
     return model
```

This is not a proposal, this is just an overview of features.
I explicitly left all implementation details out of scope for now.
So we can discuss the raw idea behind it.

**Comment by sobolevn** [comment]
The main idea is that we can still work with ORM just inside the project's repository layer.
And afterward we can cast ORM models to domain entities. That can not know anything about persistance layer.

Also, we have to work with:
1. Multiple entries in querysets -> covert to list
2. Foreign keys -> preload or not preload, depending on type of the field in domain entity `project_id: int` vs `project: Project`, we should also allow `select_related`
3. Handle m2m the similar way, including allowing `prefetch_related` in querysets

## Pipeline

The whole pipeline will look like so:
1. Create a queryset with full `django` power
2. Cast it to domain entity(ies)
3. Allow to modify these entities to modify its state via custom functions written by the developer with minimal boilerplate
4. Convert changes back or just mutate the exisiting entity

**Comment by sobolevn** [comment]
Out of scope:
1. Transactions, it is a task of the end user to handle them
2. Serialization / deserialization
3. Tweaking `django`'s behaviour 
4. Complex data transformations, use other tools to prepare your data first

**Comment by proofit404** [comment]
I don't like 

    3. Allow modifying these entities to modify its state via custom functions written by the developer with minimal boilerplate
    4. Convert changes back or just mutate the existing entity

Track object modification is a really complex task.

Usually, I just do 
```python
def set_profile_name(profile_id, profile_name):
    ProfileModel.objects.filter(pk=profile_id).update(name=profile_name)
```
The main idea is good old
    functions modifying the data should not return anything
    functions retrieving the data should not modify anything

What was changed we usually know from the scenario itself, i.e. the definition of story and it's context.

**Comment by sobolevn** [comment]
@proofit404 yes, I agree. Modifications should be done like so:

```python
def update_issue(issue: Issue, text: str) -> None:
     IssueModel.objects.filter(uid=issue.uid).update(text=text)
```

**Comment by proofit404** [comment]
Looks like we have clear goals and figured out user-facing API.

Closing then.
