### ISSUE TITLE
Support context relations.

### ISSUE THREAD

**Issue by proofit404** [dry-python/mappers#20]
We should protect decorated functions from calling them with incorrect `int`.

```python
def load_post(post_id: Post.primary_key) -> Post:
    ...

class CommentOnPost:
    def find_post(self, ctx: Context):
        return load_post(ctx.community_id) # <- error here

class Context(BaseModels):
    community_id: Community.primary_key
```
In the example above domain models are incompatible but field types are the same. Domain models should match.

**Comment by sobolevn** [comment]
This should be written using `NewType`.

**Comment by proofit404** [comment]
Yes, `typing` module handle this for us already. Thanks for the advice.
