### ISSUE TITLE
Can the documentation cover how to use the mapper for add / update user examples?

### ISSUE THREAD

**Issue by simkimsia** [dry-python/mappers#221]
Hi there, I came here via cosmicpython footnotes recommending this library under Appendix D for Django.

SEe here https://www.cosmicpython.com/book/appendix_django.html#_footnotedef_1

Because in that appendix, they cover how to write own boilerplate to have DDD for Django for both read and write. I was wondering if you can update the documentation to include add/update user examples preferably using Django ORM models?

I don't mind doing a PR but I need guidance

## update 1

Sorry i just read the tests https://github.com/dry-python/mappers/blob/master/tests/test_data_sources.py

I see that they all involve retrieval and not writes. Is it fair to say that mapper converts domain models (entities, nested entities, value objects) into ORM and then back again only for read operations?

## update 1

found https://github.com/dry-python/mappers/issues/2 which includes some use case for create, update , but not sure if there's equivalent for the create/update in the documentation

**Comment by gregbrowndev** [comment]
@simkimsia also check out the Bookshelf demo project, it has a lot more examples: 

https://github.com/dry-python/bookshelf/blob/master/bookshelf/repositories/profile.py

**Comment by simkimsia** [comment]
Thanks @gregbrowndev wouldn't have gotten this far in my experimenting with mappers without you leading the way. Btw, i agree with some of yoru feedback in gitter. The documentation can definitely be clearer and more consistent across libraries.

But still, dry-python looks 👀 highly promising 🙌

**Comment by proofit404** [comment]
At this point, we will promote the user to write own implementations of the create/update/delete functions.
In the https://github.com/dry-python/mappers/issues/174 we'll mention that mappers are deserialization library.
At some point in the future, we probably will change the goal.

**Comment by simkimsia** [comment]
Sorry just to clarify for my own understanding

Are you trying to say that ultimately mappers are only meant for read operations only?

**Comment by proofit404** [comment]
At least for now, yes.
