### ISSUE TITLE
Annotate source code

### ISSUE THREAD

**Issue by sobolevn** [dry-python/mappers#24]
Before going any further we need to annotate the source code. Since we support `python2.7` we can use `.pyi` files

Steps:
1.  Create empty `py.typed` in the root of the project
2. Create `FILENAME.pyi` files for everything
3. Type!

This is how we can ship types to the final users (which is the crucial feature for me and many others).

I can help you with this one, starting with some basics later today.

**Comment by proofit404** [comment]
Closed by https://github.com/dry-python/mappers/pull/53
