### ISSUE TITLE
Setup markdownlint.

### ISSUE THREAD

**Issue by proofit404** [dry-python/mappers#32]
https://github.com/DavidAnson/markdownlint

**Comment by sobolevn** [comment]
`remark-lint` is better, saying as a part of `remark` team 😄

**Comment by proofit404** [comment]
Is there a solution for a similar issue like this? https://github.com/DavidAnson/markdownlint/issues/197

**Comment by sobolevn** [comment]
You can actually use:
- https://github.com/eslint/eslint-plugin-markdown
- https://pypi.org/project/flake8-markdown/

**Comment by proofit404** [comment]
Actually not yet...

See https://github.com/johnfraney/flake8-markdown/issues/1

In addition, I have a concern that the library doesn't use markdown parser and run flake8 in a separate subprocess for each code block.

**Comment by proofit404** [comment]
I found this information so far:

* remarklint is able to run different linters inside codeblocks https://github.com/Qard/remark-lint-code & https://github.com/Qard/remark-lint-code-eslint 
* flake8 is able to lint doctests inside Python files https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-doctests

Let's see what we can do with it.

**Comment by proofit404** [comment]
I have set up `remark-lint` in the project. Both in Tox and Azure pipelines.
