### ISSUE TITLE
Declarative and TypeSafe relations between types.

### ISSUE THREAD

**Issue by proofit404** [dry-python/mappers#4]
I'm writing a lot of functions like this to inject them into stories.
```python
def get_community_for_post(post_id):
    return Community(**app.models.Community.objects.filter(posts=post_id).values().first())

def get_community_for_comment(comment_id):
    return Community(**app.models.Community.objects.filter(posts__comments=comment_id).values().first())
```
I don't like many namespaces in this case
```
comment.post.community.author.username
```
because each attribute can be null or not found.

I think we need [glom](https://glom.readthedocs.io/en/latest/) of databases.

With strong type inference, so I'll be sure that `comment...username` will throw 17 type errors.

**Comment by sobolevn** [comment]
Can you provide an example of how it should be?

**Comment by proofit404** [comment]
I still trying to wrap my head around it.

**Comment by sobolevn** [comment]
See https://github.com/mahmoud/glom/issues/10
