### ISSUE TITLE
Add evaluated attributes without annotation

### ISSUE THREAD

**Issue by atuchak** [dry-python/mappers#49]
Allow mapping field that does not exist in database model without using of annotation 

`annotate(attr=Value())`

Example:
`
class UserDataclass:
    name: str
    photo: str

class AdminUserDatabase:
    name: str
    # no photo

class RegularUserDatabase:
    name: str
    photo: str

# current workaround
admin_mapper = Mapper(
    UserDataclass, AdminUserDatabase,
    {
        'primary_key': 'pk',
        'photo': Evaluated(),
    }
)

regular_mapper = Mapper(
    UserDataclass, RegularUserDatabase,
    {
        'primary_key': 'pk',
    }
)

def load_admin_users():
    users = AdminUserDatabase.objects.all()
    users = users.annotate(photo=Value('photo'))
    return users

def load_regular_users():
    return RegularUserDatabase.objects.all()

`

**Comment by proofit404** [comment]
Thanks for the report! 

I'll think about what I can do.

Best regards,
Artem.

**Comment by proofit404** [comment]
The main point of Entities is behavior encapsulation.

To serve this purpose the interface of the Entity should be segregated to the minimum information required Entity methods to work.

This code example looks like you're trying to use Entity as a data structure (Value objects in the DDD terms).

If you need a data structure, you can always use `UserTable.objects.values_list()`.

If the data source misses the field required by the entity to do meaningful work, the reader function should provide value itself.

`UserTable.objects.annotate(field=Value(''))` looks like a less evil to me, than overcomplicate the library to make wrong Entity design easier.

Hope this makes sense.

Best regards,
Artem.
