### ISSUE TITLE
Complicated models

### ISSUE THREAD

**Issue by RCheese** [dry-python/mappers#54]
What's the right way to map a lot of ORM to one dataclass with mappers?

In case if I have user model with id, name and etc. and user bio profile with his weight, height and etc. I want to combine they in one dataclass for use in story.

**Comment by proofit404** [comment]
Hi,

Thanks for giving a try to the `mappers` library.

I'm not sure if a single domain entity should be split into several database tables. The most common case is quite the opposite. I.e. storing multiple domain entities in the single table.

But it's doable with `mappers` library right now.

First of all, you need to return a single query set from the function decorated with the `reader` macro. And one queryset is related to the one Django model.

The second case, you should have only one related model, not a collection of them.

For example, if there is one to one field between user and bio, you could use any of them. If there is a foreign key from bio to the user, you could use the bio model only.

To access fields of related objects in mapper you could use a tuple of strings.

Let's consider this code example:
```python
@dataclass
class Message:
    name: str
    project_name: str

class MessageModel(db.Model):
    name = db.CharField()
    channel = db.ForeignKey('ChannelModel')

class ChannelModel(db.Model):
    project = db.ForeignKey('ProjectModel')
    
class ProjectModel(db.Model):
    name = db.CharField()

mapper = Mapper(Message, MessageModel, {'project_name': ('channel', 'project', 'name')})

@mapper.reader
def load_messages() -> List[Message]:
    return MessageModel.objects.all()
```

Hope that helps.

Best regards,
Artem.
