### ISSUE TITLE
Релиз, роадмап

### ISSUE THREAD

**Issue by asyncee** [dry-python/mappers#60]
Привет!

Уже второй или третий раз наткнулся на видео о проекте dry-python, где в том числе рекламируется и эта библиотека.

Зашёл почитать документацию, посмотреть код, чтобы проанализировать, стоит ли использовать в своём pet project, а документации и релизов то и нет... :)

Посмотрев видео, я подумал что оно уже работает где-то в продакшне.

Вопрос такой — какие планы по развитию проекта и стоит ли вообще на него расчитывать в ближайшем будущем (год)?

**Comment by proofit404** [comment]
Привет! Спасибо за интерес к проекту.

Все библиотеки проекта dry-python писались как модули существующих production приложений и в последующем извлекались как open source.

Реализация и интерфейсы проверены в бою.

Но чтобы опубликовать уже написанный код нужно сильно больше усилий. Написать документацию, примеры в tutorials, покрыть тестами не зависящими от сценариев использования конкретных production приложений.

Мы потихоньку к этому идём. Все roadmap публикуются во вкладке projects профиля организации на GitHub.

В текущем состоянии мы используем собственные библиотеки из `master`.

Ближайшие годы всё будет планомерно и размеренно развиваться. т.к. данные библиотеки - ключевая часть архитектуры наших собственных production приложений.

Надеюсь помог.

С уважением, Малышев Артём.

**Comment by proofit404** [comment]
https://github.com/dry-python/mappers/issues/42 was updated correspondingly.
