### ISSUE TITLE
Allow mapper reverse elements ordering for List[]

### ISSUE THREAD

**Issue by atuchak** [dry-python/mappers#64]

**Comment by proofit404** [comment]
Why not use `order_by` query set method before returning it from the reader?

**Comment by atuchak** [comment]
I want to order db records descending, then get a slice of them [1:size]. Finally, I want the slice to be ordered ascending. I could be done by using a negative slice, but it is not supported by Django ORM.

**Comment by proofit404** [comment]
Fixing possibilities of the Django ORM is out of the scope of this package for sure.

It could be solved with another third party libraries I believe.

In its core, the `mappers` library takes prepared QuerySet and create instances of your own classes from it.

This approach working with third-party libraries like [django-pg-returning](https://github.com/M1hacka/django-pg-returning) and [django-pg-bulk-update](https://github.com/M1hacka/django-pg-bulk-update) even they return own QuerySet subclass.

I hope that makes sense.

Best regards, 
Artem.
