### ISSUE TITLE
Evaluate field in mapper

### ISSUE THREAD

**Issue by RCheese** [dry-python/mappers#65]
I have model Product with "weight of piece" param and model Ingredient with field "amount"
I would like to get summary weight in dataclass.

```python
class Product(models.Model):
	weight_of_piece = models.FloatField()

class Ingredient(models.Model):
	amount = models.FloatField()
	product = models.ForeignKey(Product)


@dataclass
class IngredientDC:
	weight: float
```

```python
ingredient_mapper = Mapper(
		IngredientDC, Ingredient, {
			'weight': Evaluate('amount') * Evaluate('product__weight_of_piece')  # As I want
		}
	)
```

**Comment by proofit404** [comment]
This will be documented at the final stage of https://github.com/dry-python/mappers/pull/61

This was implemented already but the behavior is quite different from what you describe.

`Evaluated` class is only a marker which could point `Mapper` in what field the evaluated result will be present.

You should evaluate `weight` field with QuerySet annotate method and `F` objects.

For examle, something like this:
```python
mapper = Mapper(IngredientDC, Ingredient, {'weight': Evaluated('the_weight')})

@mapper.reader
def load_ingredients() -> List[IngredientDC]
    return Ingredient.objects.annotate(
        the_weight=F('amount') * F('product__weight_of_piece'),
    )
```

P.S. If annotation field name matches target field name in the dataclass, you could ommit an argument of the `Evaluated` marker. I.e. `annotate(weight...` and `{'weight': Evaluated()}`.
