### ISSUE TITLE
Usage annotation for django models

### ISSUE THREAD

**Issue by RCheese** [dry-python/mappers#68]
If I use `models.Model` for annotation argument, I've got warning
![Screenshot from 2019-08-22 16-29-38](https://user-images.githubusercontent.com/18027348/63519002-d40cfd80-c4fa-11e9-8459-93fc657953e3.png)
cause you make `DataSource = Type[DjangoModel]`
I can apply `DataSource` explicitly but this located in file with underscore `_mapper.py`.

**Comment by sobolevn** [comment]
@RCheese can you please send a PR with the fix that works for you?

**Comment by RCheese** [comment]
@sobolevn I just can use yours `DataSource` type for annotation in my code, but import from "private" (underscore) file is not ideologically right.
If you think that is normal it's ok, else I can collect all used types in public file and send PR.

**Comment by proofit404** [comment]
Hi,

Why do you create mapper with a model instance? Mapper class accepts model classes, not instances.

Usually, we create mappers at import time, the same way we do for Django Models and dataclasses.

Mappers do some heavy lifting on this step and its' better to create it once and reuse as much as possible.

Does `Type[models.Model]` work for you?

Hope that helps.

Best regards,
Artem.

**Comment by RCheese** [comment]
@proofit404 I use model classes not instance. It's my mistake with typing.
Yes `Type[models.Model]` work for me, but I see same class (`DataSource`) in your code and I thinked, that I can use exactly this.

**Comment by proofit404** [comment]
It's better to use `Type[models.Model]` because in the future the `DataSource` type will be extended for things like a swagger definition or graphql type.
