### ISSUE TITLE
Adopt semantic release.

### ISSUE THREAD

**Issue by proofit404** [dry-python/mappers#78]
* https://github.com/semantic-release
* https://github.com/relekang/python-semantic-release

**Comment by sobolevn** [comment]
https://github.com/apps/semantic-pull-requests
https://github.com/semantic-release/semantic-release/issues/974

**Comment by proofit404** [comment]
Thanks!

**Comment by proofit404** [comment]
Closed by https://github.com/dry-python/mappers/pull/137
